# Generated by Django 3.2 on 2021-05-22 22:10

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Bölge Adı')),
                ('line', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Bölge')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Anlık Konumu')),
                ('home_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ev Konumu')),
                ('salary', models.IntegerField(verbose_name='Maaşı')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Çalışan')),
                ('field', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='employees.field', verbose_name='Çalıştığı Bölge')),
            ],
        ),
    ]
